language: elixir
elixir:
  - '1.6.5'
notifications:
  email: false
  slack: forward-financing:T7h5LRfGWsf4RLXbS0NFuf7h
env:
  global:
    - CC_TEST_REPORTER_ID=521de70fb53668d39ad37bd7abeae6529d50dad265ed314575fe46def6e4d781
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mix test --cover
  - mix coveralls.json
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT